language: node_js
node_js:
  - "8.8"
  - "7.1"
sudo: false
cache:
  directories:
    - $HOME/.yarn-cache
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
env:
  - NODE_ENV='test'
script:
  - npm test
  - npm run bundle:ios
matrix:
  include:
    - language: android
      os: linux
      jdk: oraclejdk8
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      sudo: required
      node_js: false
      before_install:
        - nvm install 7
        - node --version
        - travis_retry curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
        - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        - travis_retry sudo apt-get update -qq
        - travis_retry sudo apt-get install -y -qq yarn
      install:
        - yarn
      android:
        components:
          - tools
          - platform-tools
          - build-tools-23.0.1
          - build-tools-25.0.3
          - build-tools-26.0.1
          - android-26
          - android-26.0.1
          - android-25
          - android-23
          - extra-android-m2repository
          - extra-google-google_play_services
          - extra-google-m2repository
          - addon-google_apis-google-16
        licenses:
          - 'android-sdk-preview-license-.+'
          - 'android-sdk-license-.+'
          - 'google-gdk-license-.+'
      script:
        - cd android && ./gradlew assembleDebug && ./gradlew assembleRelease
    - language: objective-c
      os: osx
      osx_image: xcode8.3
      node_js: false
      podfile: ios/Podfile
      before_install:
        - nvm install 7
        - node --version
        - travis_retry npm install -g yarn
        - yarn -version
        - rvm install ruby-2.2.2
        - gem install cocoapods
        - gem install xcpretty -N
        - brew update
        - pod install --project-directory=ios
      install:
        - travis_retry gem install xcpretty
        - travis_retry yarn
      xcode_project: ios/Nearby.xcworkspace
      xcode_scheme: ios/NearbyTests
      script:
        - cd ios
        - xcodebuild -scheme Nearby -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
        - travis_retry xctool run-tests -scheme Nearby -sdk iphonesimulator -launch-timeout 90  ONLY_ACTIVE_ARCH=NO
